version: "3"

services:
  db:
    image: postgres:15
    restart: always
    networks:
      - data
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    shm_size: 1gb

  base-goerli-processor:
    build:
      context: ./indexers/base-goerli
    networks:
      - data
    depends_on:
      - db
    restart: always
    env_file:
      - ./indexers/base-goerli/.env

  optimism-goerli-processor:
    build:
      context: ./indexers/optimism-goerli
    networks:
      - data
    depends_on:
      - db
    restart: always
    env_file:
      - ./indexers/optimism-goerli/.env

  optimism-mainnet-processor:
    build:
      context: ./indexers/optimism-mainnet
    networks:
      - data
    depends_on:
      - db
    restart: always
    env_file:
      - ./indexers/optimism-mainnet/.env

  transformer:
    build:
      context: ./transformers
    depends_on:
      - db
    networks:
      - data

  dashboard:
    build:
      context: ./dashboard
    depends_on:
      - db
    networks:
      - data
    ports:
      - "${DASHBOARD_PORT}:8501"
    volumes:
      - ${LEGACY_DB_LOCATION}:/app/data/perps.db

networks:
  data:
    driver: bridge
