
version: 2

models:
  - name: base_goerli_perps_account_created
    description: "AccountCreated events from the PerpsMarketProxy contract"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
