
version: 2

models:
  - name: perp_account_created
    description: "AccountCreated events from the PerpsMarketProxy contract"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: perp_order_committed
    description: "OrderCommitted events from the PerpsMarketProxy contract"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: perp_order_settled
    description: "OrderSettled events from the PerpsMarketProxy contract"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: perp_market_updated
    description: "MarketUpdated events from the PerpsMarketProxy contract"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: perp_position_liquidated
    description: "PositionLiquidated events from the PerpsMarketProxy contract"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: perp_account_liquidated
    description: "AccountLiquidated events from the PerpsMarketProxy contract"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: perp_collateral_modified
    description: "CollateralModified events from the PerpsMarketProxy contract"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: perp_previous_order_expired
    description: "PreviousOrderExpired events from the PerpsMarketProxy contract"
    columns:
      - name: id
        tests:
          - unique
          - not_null
